version: "3.8"

services:
  backend:
    build: .
    image: maze_api
    restart: always
    container_name: maze_api
    ports:
      - "${PORT}:5000"
    volumes:
      - "./:/usr/src/app"
      - "${DOCKER_STATIC_HOSTING}:/usr/src/app/static"
    environment:
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONIOENCODING: ${PYTHONIOENCODING}
    networks:
      - https

networks:
  https:
    name: ${HTTPS_NETWORK}
    external: true
