# Generated by Django 3.1.2 on 2020-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maze",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.IntegerField(default=20)),
                ("height", models.IntegerField(default=20)),
                ("maze_json", models.JSONField(default=dict)),
                ("include_steps", models.BooleanField(default=False)),
                (
                    "solution_type",
                    models.CharField(
                        choices=[
                            ("do_not_include", "Do Not Include"),
                            ("include_solution", "Include Solution"),
                            ("include_steps", "Include Solution with Solution Steps"),
                        ],
                        default="do_not_include",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
